### ISSUE TITLE
Prompt is triggered when new files are created during Obsidian Sync

### ISSUE THREAD

**Issue by cakechaser** [numeroflip/obsidian-auto-template-prompt#2]
Thanks for the plugin, I was just thinking that something like this would be useful!

I found an issue with Obsidian Sync.

1. Create a file on 1st device
2. Open Obsidian on 2nd device
3. The file will be synched to the 2nd device, when it's created, a prompt for a template will pop up

If there are multiple new files being synched, multiple prompts will open one after another, and will need to be closed one by one.

I would expect that the prompt would appear only if a brand new file is created manually.

**Comment by numeroflip** [comment]
@cakechaser  I just published a new version, which intends to fix that. ( version `1.0.4` ) 
Would you kindly check if the problem fully solved by it or not?

**Comment by cakechaser** [comment]
Works great now, thank you for the quick fix!
