### ISSUE TITLE
Pop-up triggers for existing notes

### ISSUE THREAD

**Issue by cakechaser** [numeroflip/obsidian-auto-template-prompt#9]
How to reproduce:
1) I had a folder with some notes
2) Renamed the folder. The way Obsidian sync works, it will delete the folder with all the notes inside, and re-upload the folder with the new name along with all the notes. So renaming a folder with 100 files will trigger the deletion and upload of 100 files
3) Now when I open some of the files which were in this folder, the pop-up is triggered

After this operation the re-uploaded files have the same created/modified timestamps.
I guess the plugin checks the created/modified time of the file, and triggers the pop-up if the times are matching.

One possible fix would be to check if the file contains any text or if it's empty

**Comment by numeroflip** [comment]
That's an interesting edge case indeed.  

I just published version `1.1.1`, where it now checks if the file is actually empty or not, as you recommended :) .

Would you kindly check now this specific issue is solved correctly?

**Comment by cakechaser** [comment]
Works perfectly now, thanks for the quick resolution!
